@route = http://localhost:7000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiIxMjM0NTZAc3R1ZGVudC5iZWxnaXVtY2FtcHVzLmFjLnphIiwianRpIjoiMzNjNGZjZTYtMjJlMC00YzA3LThkMjUtNzlkOWRkZWU4MGQ0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkpvaG4gRG9lIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3R1ZGVudCIsIlVzZXJQcm9maWxlSUQiOiIxIiwiU3R1ZGVudE51bWJlciI6IjEyMzQ1NiIsIlF1YWxpZmljYXRpb24iOiJCSVQiLCJGdWxsTmFtZSI6IkpvaG4gRG9lIiwiSXNBY3RpdmUiOiJUcnVlIiwiSXNTdHVkZW50IjoiVHJ1ZSIsIklzVHV0b3IiOiJGYWxzZSIsIklzQWRtaW4iOiJGYWxzZSIsImV4cCI6MTc2MDA5MTc3MCwiaXNzIjoiQ2FtcHVzTGVhcm4uVXNlck1hbmFnZW1lbnQiLCJhdWQiOiJDYW1wdXNMZWFybi5TZXJ2aWNlcyJ9.IMCZ1q_ywEeirY8jIKlsHbsc0deo9rSE-hhD4FIbW9g

GET {{route}}/user/users
Accept: application/json
Authorization: Bearer {{token}}
###

GET {{route}}/user/users/migration
Accept: application/json
Authorization: Bearer {{token}}
###

### Register a new Student
POST {{route}}/authentication/auth/register
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe", 
  "email": "123456@student.belgiumcampus.ac.za",
  "password": "Password123!",
  "userRole": 0,
  "qualification": 1,
  "studentNumber": 123456
}

### Register a new Tutor
POST {{route}}/authentication/auth/register
Content-Type: application/json

{
  "name": "Jane",
  "surname": "Smith",
  "email": "789012@student.belgiumcampus.ac.za",
  "password": "TutorPass123!",
  "userRole": 1,
  "qualification": 2,
  "studentNumber": 789012
}


### Register a new Admin
POST {{route}}/authentication/auth/register
Content-Type: application/json

{
  "name": "Peter",
  "surname": "Ndoda",
  "email": "80000@student.belgiumcampus.ac.za",
  "password": "AdminPass123!",
  "userRole": 2,
  "qualification": 2,
  "studentNumber": 80000
}

### Login as Student
POST {{route}}/authentication/auth/login
Content-Type: application/json

{
  "email": "123456@student.belgiumcampus.ac.za",
  "password": "Password123!"
}

### Login as Tutor  
POST {{route}}/authentication/auth/login
Content-Type: application/json

{
  "email": "789012@student.belgiumcampus.ac.za",
  "password": "TutorPass123!"
}

### Login as Admin  
POST {{route}}/authentication/auth/login
Content-Type: application/json

{
  "email": "80000@student.belgiumcampus.ac.za",
  "password": "AdminPass123!"
}

### Validate Token (Protected route example)
POST {{route}}/authentication/auth/validate-token
Content-Type: application/json

{
  "token": "{{token}}"
}
