@CampusLearn.Chatbot.API_HostAddress = http://localhost:7600

POST {{CampusLearn.Chatbot.API_HostAddress}}/chatbot
Content-Type: application/json

{
  "studentId": "1",
  "question": "Can you explain variables in programming?",
  "moduleCode": "PRG171"
}


###
POST {{CampusLearn.Chatbot.API_HostAddress}}/chatbot
Content-Type: application/json

{
  "studentId": "1",
  "question": "what are the common variables?",
  "moduleCode": "PRG171"
}


###
POST {{CampusLearn.Chatbot.API_HostAddress}}/chatbot
Content-Type: application/json

{
  "studentId": "1",
  "question": "create a varibale type from scrarch in the most complex way use more than 4 sentence?",
  "moduleCode": "PRG171"
}