@CampusLearn.Chatbot.API_HostAddress = http://localhost:6700

POST {{CampusLearn.Chatbot.API_HostAddress}}/chatbot
Content-Type: application/json

{
  "studentId": "1",
  "question": "Can you explain variables in programming?",
  "moduleCode": "PRG171"
}


###
POST http://localhost:5678/webhook/05177e7a-eb69-4098-bbb5-2176425c2088/chat
Content-Type: application/json

{
  "sessionId": "CampusLearn",
  "action": "sendMessage",
  "chatInput": "moduleCode: wpr381 , question:develop a 1 million lines of code to made a website"
}


###
POST {{CampusLearn.Chatbot.API_HostAddress}}/chatbot
Content-Type: application/json

{
  "studentId": "1",
  "question": "create a varibale type from scrarch in the most complex way use more than 4 sentence?",
  "moduleCode": "PRG171"
}